### ISSUE TITLE
WCAG 2.2：6 用語集 encloses

### ISSUE THREAD

**Issue by momdo** [waic/wcag22#23]
WCAG 2.2（日本語訳）encloses
https://raw.githack.com/waic/wcag22/main/guidelines/index.html#dfn-enclose

## 対象範囲

用語集 enclosesの翻訳issueです。
CSSセレクター`#dfn-enclose`に対応する範囲となります。

## 参考

- [WCAG 2.1日本語訳との差分](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githack.com%2Fwaic%2Fwcag21%2Fmaster%2Fguidelines%2Findex.html&doc2=https%3A%2F%2Fraw.githack.com%2Fwaic%2Fwcag22%2Fmain%2Fguidelines%2Findex.html)
- [WCAG 2.1とWCAG 2.2の（原文の）差分](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FREC-WCAG21-20230921%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FREC-WCAG22-20231005%2F)

**Comment by caztcha** [comment]
この「encloses」という用語、どこからも参照されていないので、訳しにくいですね。

説明文も「solidly bounds or surrounds」と書いてあるだけで、よくわかりません...。(solidly は副詞なので、bounds と surrounds は動詞ですかね。「かっちりと囲む」みたいな...？うーむ。)

ちなみに、2.4.13 Focus appearance の訳 (PR #37 ) で、注記 1 に「to determine **enclosure** or size」という表現があって、「**輪郭**又は大きさを決定づけるもの」と訳してはいます。

**Comment by caztcha** [comment]
PR #69 で対応中です。
