### ISSUE TITLE
未訳の解説書に冒頭訳註を入れる

### ISSUE THREAD

**Issue by bakera** [waic/wcag22#333]
WCAG 2.2解説書は新規達成基準のみ日本語訳した状態で一旦公開する
未訳の解説書には冒頭訳註を入れて、対応する2.1日本語訳に誘導する

**Comment by bakera** [comment]
訳註の内容を決めて、追加する作業を行えば良い

**Comment by bakera** [comment]
いったんHTML上は2.1解説書トップにリンクする
JSで対応する解説書のURLに書き換える (余裕があれば)

**Comment by bakera** [comment]
2.0解説書の冒頭の訳註はこんな感じ
```
【注意】この文書にはより新しいバージョンが存在します: [WCAG 2.1 解説書](https://waic.jp/translations/WCAG21/Understanding/)
```

**Comment by bakera** [comment]
こうする?
```
このWCAG 2.2解説書の日本語訳は作業中となっています。
WCAG 2.1解説書の日本語訳をご利用いただけます。
[WCAG 2.1 解説書](https://waic.jp/translations/WCAG21/Understanding/)
```

**Comment by bakera** [comment]
WCAG 2.0 解説書の注を見るとclassなしのdivなんですね……。
スタイルをつけようという気持ちが一切ない、というのはいいのですが、scriptで操作しようとするとなにかしら目印は必要ですね。

```
<div><p>【注意】この文書にはより新しいバージョンが存在します: <a href="[/translations/WCAG21/Understanding/](https://waic.jp/translations/WCAG21/Understanding/)">WCAG 2.1 解説書</a></p></div>
```

**Comment by bakera** [comment]
あと今更気づいたんですが、最近の解説書のスタイルはそれなりにちゃんとしたヘッダがついてるんで、本当にbody直後に訳註を入れるとヘッダの上に入ってしまうんですね。
![スクリーンショット: ヘッダの上に注釈が入るパターン](https://github.com/user-attachments/assets/c5f068d6-99ab-4a9e-af82-8c1580bf1893)

**Comment by bakera** [comment]
mainの中に入れるのもありか?

![main要素の中に注釈を入れるパターン](https://github.com/user-attachments/assets/1a17cc8d-667a-4b9a-b7d1-f4dfe8aa30d8)

**Comment by momdo** [comment]
@bakera 

> mainの中に入れるのもありか?

よいのではないでしょうか…！

**Comment by caztcha** [comment]
私も、`<main>` の直下に入れる、でよいかと思います。

ちなみに細かい話ですが、この解説書をタブレット以下のサイズ (幅 960 px 未満) でみると、目次 (Page Contents) が `<main>` よりも上に配置されるので、`<main>` の直下にこの訳注を入れると、下の画像のように目次の下に訳注が表示される形になります。個人的には、ありかなと思いますが、いかがでしょうか？

<img width="1180" alt="WCAG 2.2 解説書をタブレット以下の画面幅で表示" src="https://github.com/user-attachments/assets/f11c8261-2d19-4d04-a844-48d8c813b28a">

目次 (`<aside>` 要素) の上に訳注を置くこともいくつか試したのですが、その場合、この訳注用にスタイリングを別途書かないと収まりが悪い感じです。わざわざ一時的な訳注のために CSS を書くのもどうかな、と思いました...。

**Comment by momdo** [comment]
@caztcha 

> 個人的には、ありかなと思いますが、いかがでしょうか？

よいと思います！（「気持ち悪さ」があったとしても、とっとと日本語化してしまえばいいだけですし）

**Comment by caztcha** [comment]
@momdo ありがとうございます。
@bakera よろしければ、`<main>` の開始タグ直下に訳注を入れる形で、プルリク作成してよいでしょうか？

**Comment by bakera** [comment]
はい、問題ないと思います!

**Comment by caztcha** [comment]
@bakera @momdo 
お待たせいたしました。プルリクエストを出しましたので、ご確認いただけますと幸いです！ #335

**Comment by bakera** [comment]
JavaScriptでリンク先を個別ぺージに書き換える想定ですので、classかidが欲しいですね。
https://github.com/waic/wcag22/issues/333#issuecomment-2439982003

(もしくは最初から個別ページへのリンクにしておいても良いのですけど、面倒がない方で)

**Comment by caztcha** [comment]
@bakera 

ありがとうございます。たしかに、そうですよね。

```
<!-- 日本語訳されるまでの一時的な注記 -->
<div class="untranslated-note">
<p>このWCAG 2.2 解説書の日本語訳は作業中となっています。WCAG 2.1 解説書の日本語訳をご利用いただけます。<br>[ <a href="https://waic.jp/translations/WCAG21/Understanding/">WCAG 2.1 解説書</a> ]</p>
</div>
```
↑こんなふうに `div` に class をつけて (ちょっと長いかもですが、一見して意味が伝わりやすい感じで untranslated-note というクラス名にしています)、そのうえで、各ページの最下部 ( `</body>` の直前) に下記の JS を書く形で、いかがでしょうか？(JS を自分では書けないので、ChatGPT に教えてもらいました。ローカルで試したら一応意図通りに動作しました。)

```
   <!-- 日本語訳されるまでの一時的な JS -->
   <script>
     document.querySelectorAll('.untranslated-note a').forEach(link => {
      // 現在のページのファイル名を取得
      const filename = window.location.pathname.split('/').pop().replace('.html', '');
      // 元の href を流用して新しい URL を設定
      link.href = `${link.href}${filename}.html`;
     });
   </script>
```

**Comment by bakera** [comment]
AIでいけるとは!
あとはChatGPTに「DOMContentLoadedのタイミングで動作するようにしてくれ」と注文してみていただけると完成するかもしれません。

**Comment by caztcha** [comment]
なるほどです！

こんな感じの JS を外部ファイル化して、`<head>` 内に `<script src="hoge.js"></script>` を書いて読み込ませる、という感じでしょうか。(.js のファイル名は、「untranslated-note.js」みたいな名前でよいですかね...？)

```
document.addEventListener('DOMContentLoaded', () => {
    // .untranslated-note クラスを持つ div 内の a タグを取得
    document.querySelectorAll('.untranslated-note a').forEach(link => {
        // 現在のページのファイル名を取得
        const filename = window.location.pathname.split('/').pop().replace('.html', '');
        
        // 元の href を流用して新しい URL を設定
        link.href = `${link.href}${filename}.html`;
    });
});
```

**Comment by bakera** [comment]
コードもファイル名も良いと思います!

いちおう少しだけ気になった瑣末な点として、訳註リンクはたぶん1つだけなので、 querySelectorAll して forEach しなくても querySelector で処理するほうが早いような気はします。
あと filename から一度 `.html` を取り除いて最後にもう一度 `.html` をつけているのですが、これは .html があってもなくても .html へリンクさせるという意図かと思います。実際には .html はあってもなくてもアクセスできるようになっているので、これはどちらでも良さそうです。
たとえば以下のようなコードでも良いと思います。このへんはお好みなので、いただいたものそのままでも良いと思います。

```
document.addEventListener('DOMContentLoaded', () => {
    const targetAnchor = document.querySelector('.untranslated-note a');
    if(!targetAnchor) return;
    const currentFilename = window.location.pathname.split('/').pop();
    targetAnchor.href = targetAnchor.href + currentFilename;
});
```

**Comment by caztcha** [comment]
@bakera ありがとうございます！ `forEach` は、私もなんとなくもやもやしていたので、助かりました。
手元で試してみて、あらためてプルリクエスト更新させていただきます！

**Comment by caztcha** [comment]
@bakera @momdo 

改めまして、プルリクエスト #335 を更新し、JS も追加してみました。
ただ、実際に JS が効いているのかを、GitHub 上で挙動を確かめる方法がわからず...

https://htmlpreview.github.io/

で試したのですが、たとえば下記のページでは、うまく JS が働いていないようでした。

https://htmlpreview.github.io/?https://raw.githubusercontent.com/waic/wcag22/tsuchiya-edit-understanding-untranslated-note/understanding/non-text-content.html

JS の書きかたが悪いのか、htmlpreview.github.io の仕様上の制約なのか、よくわからないのですが、なにか解決方法ご存知でしたら、教えていただけますと幸いです。

**Comment by momdo** [comment]
@caztcha 

もしかして：`class`属性を書き忘れている

```html
<div class="untranslated-note">
```

**Comment by caztcha** [comment]
@momdo ありがとうございます！まさかのポカで、大変お恥ずかしい...。
プルリクエスト、修正しました。改めてプルリクエスト側に、レビュー依頼のコメント入れますので、よろしくお願いいたします。
