### ISSUE TITLE
「3.3.8 アクセシブルな認証 (最低限)」と「3.3.9 アクセシブルな認証 (高度)」の「事例」の翻訳

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag22#341]
この2つ、英文がまったく同じなのに、翻訳に違いがあります。
翻訳も一致させるべきではないでしょうか？

https://w3c.github.io/wcag/understanding/accessible-authentication-minimum
> A web site that requires two-factor authentication allows for multiple options for the 2nd factor, including a USB-based method where the user simply presses a button to enter a time-based token.

https://dev.waic.jp/translations/WCAG22/Understanding/accessible-authentication-minimum.html
> 2 要素認証を必要とするウェブサイトは、利用者がボタンを押すだけで時間ベースのトークンを入力する USB ベースの方法など、2 要素認証について複数のオプションをが可能にする。

https://w3c.github.io/wcag/understanding/accessible-authentication-enhanced.html
> A web site that requires two-factor authentication allows for multiple options for the 2nd factor, including a USB-based method where the user simply presses a button to enter a time-based token.

https://dev.waic.jp/translations/WCAG22/Understanding/accessible-authentication-enhanced.html
> 2 要素認証を必要とするウェブサイトは、利用者がボタンを押すだけで時間ベースのトークンを入力する USB ベースの方法など、2 要素認証について複数のオプションを許容する。

**Comment by momdo** [comment]
https://github.com/waic/wcag22/pull/299#discussion_r1724469624 を反映し切れていなかったようなので、そちらにあわせる
