### ISSUE TITLE
「3.2.6 一貫したヘルプ」の「シリアル順序」について

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag22#343]
> ヘルプ項目が視覚的には異なる場所にあるものの、同じシリアル順序で配置されている場合、利用者の観点からは役に立たないが、この基準に失敗することにはならない。

> If the help item is visually in a different location, but in the same serial order, that is not helpful from a user's point of view, but it would not fail this criterion.

「シリアル順序」は、固有の言葉のように見えますが、意味が分かりづらいです。
同じページ内で、または他のページでserializedが、「線形」とされていますし、「線形順序」としたほうがわかりやすいのではないでしょうか？

**Comment by momdo** [comment]
- 関連：https://github.com/waic/wcag20/issues/215

> 同じページ内で、または他のページでserializedが、「線形」とされていますし

https://www.w3.org/TR/WCAG22/#consistent-help

> For this Success Criterion, "the same order relative to other page content" can be thought of as how the content is ordered when the page is serialized. 

https://waic.jp/translations/WCAG22/#consistent-help

>この達成基準における「他のページコンテンツに対して相対的に同じ順序」は、ページが線形化されたときのコンテンツの並べ方と考えることができる。

個人的にはシリアライズとリニアライズを同じ「線形」としてしまってよいのかは微妙ですが、ともあれ達成基準の注記二層あるので、それにあわせることにします。
