### ISSUE TITLE
「2.4.11 隠されないフォーカス (最低限)」「2.4.12 隠されないフォーカス (高度)」での `could also meet` について

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag22#344]
> 利用者のアクションを必要としない通知も、フォーカスが失なわれるときに閉じることでこの基準を満たす可能性がある。

> Notifications that do not require user action could also meet this criterion by closing on loss of focus.

 `could also meet` は、「可能性がある」よりしっかりと満たすことを明言しているように見受けられます。「満たす」と言い切っていいように思いました。「可能性がある」は不要では？（「2.4.12 隠されないフォーカス (高度)」でも同様です）

**Comment by momdo** [comment]
「可能性がある」というよりかは「できる」とするのはありなのかもしれませんがいかがでしょう？　@bakera

**Comment by bakera** [comment]
満たすことができる、ですかね?
