### ISSUE TITLE
「2.4.11 隠されないフォーカス (最低限)」「2.4.12 隠されないフォーカス (高度)」の `never be obscured` について

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag22#345]
> この達成方法の意図は、どちらの状況にせよ、利用者がどの項目にフォーカスがあるのか判断できないほどにフォーカスを受け取るコンポーネントが隠されるべきではない、ということである。

> The intention in both situations is that the component receiving focus should never be obscured to the point a user cannot tell which item has focus.

Google翻訳では、`never be obscured` を「不明瞭にならないようにする」と訳していました。

達成基準名にも使われている言葉なので、別の訳語をあてるのは推奨されないかもしれませんが、段落の意図からすると、「不明瞭」のほうがわかりやすく感じました。（「2.4.12 隠されないフォーカス (高度)」でも同様です）

**Comment by momdo** [comment]
他の訳語を当てるつもりはないのでClose
